major fixes. MCTS ouputs a dictionary of state to actions. Some issues in game finishing.
Exception: Failed to apply action. Because game is already finished.

This is most liekely due to stack running to 0 or something similar